from datetime import date

ROUTINE = [
    {
        "subject":  "bangla",
        "paper":    "1",
        "name":     "বাংলা ১ম পত্র-১",
        "date":     "2026-02-17",
        "duration": "1:30",
        "syllabus": "গদ্য",
        "marks":    "MCQ: 30 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "phys",
        "paper":    "1",
        "name":     "Physics 1st Paper-1",
        "date":     "2026-02-19",
        "duration": "1:50",
        "syllabus": "Chapter: 2, 3, 4",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "chem",
        "paper":    "1",
        "name":     "Chemistry 1st Paper-1",
        "date":     "2026-02-22",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 2",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "eng",
        "paper":    "1",
        "name":     "English 1st Paper-1",
        "date":     "2026-02-24",
        "duration": "1:50",
        "syllabus": "Reading, Paragraph",
        "marks":    "MCQ: N/A | CQ: N/A | Written: 60",
    },
    {
        "subject":  "hmath",
        "paper":    "1",
        "name":     "Higher Math 1st Paper-1",
        "date":     "2026-02-26",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 5, 8",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "ict",
        "paper":    None,
        "name":     "ICT-1",
        "date":     "2026-02-28",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 3, 5",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bio",
        "paper":    "1",
        "name":     "Biology 1st Paper-1",
        "date":     "2026-03-02",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 2, 3, 12",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bangla",
        "paper":    "2",
        "name":     "বাংলা ২য় পত্র-১",
        "date":     "2026-03-04",
        "duration": "1:30",
        "syllabus": "ব্যাকরণ + নির্মিতি (পারিভাষিক শব্দ, বাংলা অনুবাদ)",
        "marks":    "MCQ: N/A | CQ: N/A | Written: 50",
    },
    {
        "subject":  "phys",
        "paper":    "2",
        "name":     "Physics 2nd Paper-1",
        "date":     "2026-03-06",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 2, 3, 11",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "chem",
        "paper":    "2",
        "name":     "Chemistry 2nd Paper-1",
        "date":     "2026-03-08",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 5",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "eng",
        "paper":    "2",
        "name":     "English 2nd Paper-1",
        "date":     "2026-03-10",
        "duration": "1:30",
        "syllabus": "Grammar (Article, Preposition, Gap filling with clues (special phrases/words), Completing sentences, Right form of verbs, Connectors). Writing (Email/formal letter, Composition)",
        "marks":    "MCQ: N/A | CQ: N/A | Written: 52",
    },
    {
        "subject":  "hmath",
        "paper":    "2",
        "name":     "Higher Math 2nd Paper-1",
        "date":     "2026-03-12",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 2, 6",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "ict",
        "paper":    None,
        "name":     "ICT-2",
        "date":     "2026-03-14",
        "duration": "1:50",
        "syllabus": "Chapter: 2, 4, 6",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bio",
        "paper":    "2",
        "name":     "Biology 2nd Paper-1",
        "date":     "2026-03-16",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 2, 3",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bangla",
        "paper":    "1",
        "name":     "বাংলা ১ম পত্র-২",
        "date":     "2026-03-28",
        "duration": "1:30",
        "syllabus": "পদ্য",
        "marks":    "MCQ: 30 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "phys",
        "paper":    "1",
        "name":     "Physics 1st Paper-2",
        "date":     "2026-03-30",
        "duration": "1:50",
        "syllabus": "Chapter: 1, 5, 6, 7",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "chem",
        "paper":    "1",
        "name":     "Chemistry 1st Paper-2",
        "date":     "2026-04-01",
        "duration": "1:50",
        "syllabus": "Chapter: 3, 5",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "eng",
        "paper":    "1",
        "name":     "English 1st Paper-2",
        "date":     "2026-04-03",
        "duration": "1:30",
        "syllabus": "Writing, Rearrange",
        "marks":    "MCQ: N/A | CQ: N/A | Written: 50",
    },
    {
        "subject":  "hmath",
        "paper":    "1",
        "name":     "Higher Math 1st Paper-2",
        "date":     "2026-04-05",
        "duration": "1:50",
        "syllabus": "Chapter: 3, 10",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bio",
        "paper":    "1",
        "name":     "Biology 1st Paper-2",
        "date":     "2026-04-07",
        "duration": "1:50",
        "syllabus": "Chapter: 4, 5, 6, 7",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bangla",
        "paper":    "2",
        "name":     "বাংলা ২য় পত্র-২",
        "date":     "2026-04-09",
        "duration": "1:50",
        "syllabus": "নির্মিতি: দিনলিপি লিখন, অভিজ্ঞতা বর্ণনা, ভাষণ, প্রতিবেদন, বৈদ্যুতিক চিঠি, ক্ষুদে বার্তা, পত্র লিখন, আবেদন পত্র, সারাংশ, সারমর্ম, সারসংক্ষেপ, ভাব-সম্প্রসারণ, সংলাপ রচনা, ক্ষুদে গল্প রচনা, প্রবন্ধ-নিবন্ধ রচনা",
        "marks":    "MCQ: N/A | CQ: N/A | Written: 60",
    },
    {
        "subject":  "phys",
        "paper":    "2",
        "name":     "Physics 2nd Paper-2",
        "date":     "2026-04-11",
        "duration": "1:50",
        "syllabus": "Chapter: 4, 5, 8",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "chem",
        "paper":    "2",
        "name":     "Chemistry 2nd Paper-2",
        "date":     "2026-04-13",
        "duration": "1:50",
        "syllabus": "Chapter: 2",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "eng",
        "paper":    "2",
        "name":     "English 2nd Paper-2",
        "date":     "2026-04-16",
        "duration": "1:30",
        "syllabus": "Grammar (Changing sentences, Narration, Pronoun references, Modifiers, Synonyms & Antonyms, Punctuation). Writing (Paragraph, Report)",
        "marks":    "MCQ: N/A | CQ: N/A | Written: 48",
    },
    {
        "subject":  "hmath",
        "paper":    "2",
        "name":     "Higher Math 2nd Paper-2",
        "date":     "2026-04-18",
        "duration": "1:50",
        "syllabus": "Chapter: 3, 4, 5",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bio",
        "paper":    "2",
        "name":     "Biology 2nd Paper-2",
        "date":     "2026-04-20",
        "duration": "1:50",
        "syllabus": "Chapter: 4, 5, 6, 7, 12",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bangla",
        "paper":    "1",
        "name":     "বাংলা ১ম পত্র-৩",
        "date":     "2026-04-22",
        "duration": "1:30",
        "syllabus": "উপন্যাস + নাটক",
        "marks":    "MCQ: 30 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "phys",
        "paper":    "1",
        "name":     "Physics 1st Paper-3",
        "date":     "2026-04-24",
        "duration": "1:50",
        "syllabus": "Chapter: 8, 9, 10",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "chem",
        "paper":    "1",
        "name":     "Chemistry 1st Paper-3",
        "date":     "2026-04-26",
        "duration": "1:50",
        "syllabus": "Chapter: 4",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "hmath",
        "paper":    "1",
        "name":     "Higher Math 1st Paper-3",
        "date":     "2026-04-28",
        "duration": "1:50",
        "syllabus": "Chapter: 2, 6, 7",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bio",
        "paper":    "1",
        "name":     "Biology 1st Paper-3",
        "date":     "2026-04-30",
        "duration": "1:50",
        "syllabus": "Chapter: 8, 9, 10, 11",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "phys",
        "paper":    "2",
        "name":     "Physics 2nd Paper-3",
        "date":     "2026-05-02",
        "duration": "1:50",
        "syllabus": "Chapter: 6, 7, 9, 10",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "chem",
        "paper":    "2",
        "name":     "Chemistry 2nd Paper-3",
        "date":     "2026-05-04",
        "duration": "1:50",
        "syllabus": "Chapter: 3, 4",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "hmath",
        "paper":    "2",
        "name":     "Higher Math 2nd Paper-3",
        "date":     "2026-05-06",
        "duration": "1:50",
        "syllabus": "Chapter: 7, 8",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "bio",
        "paper":    "2",
        "name":     "oogy 2nd Paper-3",
        "date":     "2026-05-08",
        "duration": "1:50",
        "syllabus": "Chapter: 8, 9, 10, 11",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "hmath",
        "paper":    "1",
        "name":     "Higher Math 1st Paper-4",
        "date":     "2026-05-10",
        "duration": "1:50",
        "syllabus": "Chapter: 4, 9",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
    {
        "subject":  "hmath",
        "paper":    "2",
        "name":     "Higher Math 2nd Paper-4",
        "date":     "2026-05-12",
        "duration": "1:50",
        "syllabus": "Chapter: 9, 10",
        "marks":    "MCQ: 25 | CQ: 30 | Written: N/A",
    },
]